// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	openreportsiov1alpha1 "github.com/openreports/reports-api/apis/openreports.io/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterReportLister helps list ClusterReports.
// All objects returned here must be treated as read-only.
type ClusterReportLister interface {
	// List lists all ClusterReports in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*openreportsiov1alpha1.ClusterReport, err error)
	// Get retrieves the ClusterReport from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*openreportsiov1alpha1.ClusterReport, error)
	ClusterReportListerExpansion
}

// clusterReportLister implements the ClusterReportLister interface.
type clusterReportLister struct {
	listers.ResourceIndexer[*openreportsiov1alpha1.ClusterReport]
}

// NewClusterReportLister returns a new ClusterReportLister.
func NewClusterReportLister(indexer cache.Indexer) ClusterReportLister {
	return &clusterReportLister{listers.New[*openreportsiov1alpha1.ClusterReport](indexer, openreportsiov1alpha1.Resource("clusterreport"))}
}
