/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	openreportsiov1alpha1 "openreports.io/apis/openreports.io/v1alpha1"
)

// ClusterReportLister helps list ClusterReports.
// All objects returned here must be treated as read-only.
type ClusterReportLister interface {
	// List lists all ClusterReports in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*openreportsiov1alpha1.ClusterReport, err error)
	// Get retrieves the ClusterReport from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*openreportsiov1alpha1.ClusterReport, error)
	ClusterReportListerExpansion
}

// clusterReportLister implements the ClusterReportLister interface.
type clusterReportLister struct {
	listers.ResourceIndexer[*openreportsiov1alpha1.ClusterReport]
}

// NewClusterReportLister returns a new ClusterReportLister.
func NewClusterReportLister(indexer cache.Indexer) ClusterReportLister {
	return &clusterReportLister{listers.New[*openreportsiov1alpha1.ClusterReport](indexer, openreportsiov1alpha1.Resource("clusterreport"))}
}
