// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ClusterReportListerExpansion allows custom methods to be added to
// ClusterReportLister.
type ClusterReportListerExpansion interface{}

// ReportListerExpansion allows custom methods to be added to
// ReportLister.
type ReportListerExpansion interface{}

// ReportNamespaceListerExpansion allows custom methods to be added to
// ReportNamespaceLister.
type ReportNamespaceListerExpansion interface{}
