/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	openreportsiov1alpha1 "github.com/openreports/reports-api/apis/openreports.io/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ReportLister helps list Reports.
// All objects returned here must be treated as read-only.
type ReportLister interface {
	// List lists all Reports in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*openreportsiov1alpha1.Report, err error)
	// Reports returns an object that can list and get Reports.
	Reports(namespace string) ReportNamespaceLister
	ReportListerExpansion
}

// reportLister implements the ReportLister interface.
type reportLister struct {
	listers.ResourceIndexer[*openreportsiov1alpha1.Report]
}

// NewReportLister returns a new ReportLister.
func NewReportLister(indexer cache.Indexer) ReportLister {
	return &reportLister{listers.New[*openreportsiov1alpha1.Report](indexer, openreportsiov1alpha1.Resource("report"))}
}

// Reports returns an object that can list and get Reports.
func (s *reportLister) Reports(namespace string) ReportNamespaceLister {
	return reportNamespaceLister{listers.NewNamespaced[*openreportsiov1alpha1.Report](s.ResourceIndexer, namespace)}
}

// ReportNamespaceLister helps list and get Reports.
// All objects returned here must be treated as read-only.
type ReportNamespaceLister interface {
	// List lists all Reports in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*openreportsiov1alpha1.Report, err error)
	// Get retrieves the Report from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*openreportsiov1alpha1.Report, error)
	ReportNamespaceListerExpansion
}

// reportNamespaceLister implements the ReportNamespaceLister
// interface.
type reportNamespaceLister struct {
	listers.ResourceIndexer[*openreportsiov1alpha1.Report]
}
