/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	openreportsiov1alpha1 "github.com/openreports/reports-api/apis/openreports.io/v1alpha1"
	scheme "github.com/openreports/reports-api/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ClusterReportsGetter has a method to return a ClusterReportInterface.
// A group's client should implement this interface.
type ClusterReportsGetter interface {
	ClusterReports() ClusterReportInterface
}

// ClusterReportInterface has methods to work with ClusterReport resources.
type ClusterReportInterface interface {
	Create(ctx context.Context, clusterReport *openreportsiov1alpha1.ClusterReport, opts v1.CreateOptions) (*openreportsiov1alpha1.ClusterReport, error)
	Update(ctx context.Context, clusterReport *openreportsiov1alpha1.ClusterReport, opts v1.UpdateOptions) (*openreportsiov1alpha1.ClusterReport, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*openreportsiov1alpha1.ClusterReport, error)
	List(ctx context.Context, opts v1.ListOptions) (*openreportsiov1alpha1.ClusterReportList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *openreportsiov1alpha1.ClusterReport, err error)
	ClusterReportExpansion
}

// clusterReports implements ClusterReportInterface
type clusterReports struct {
	*gentype.ClientWithList[*openreportsiov1alpha1.ClusterReport, *openreportsiov1alpha1.ClusterReportList]
}

// newClusterReports returns a ClusterReports
func newClusterReports(c *OpenreportsV1alpha1Client) *clusterReports {
	return &clusterReports{
		gentype.NewClientWithList[*openreportsiov1alpha1.ClusterReport, *openreportsiov1alpha1.ClusterReportList](
			"clusterreports",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *openreportsiov1alpha1.ClusterReport { return &openreportsiov1alpha1.ClusterReport{} },
			func() *openreportsiov1alpha1.ClusterReportList { return &openreportsiov1alpha1.ClusterReportList{} },
		),
	}
}
