version: 2
updates:
  - package-ecosystem: gomod
    directories:
      - /
    schedule:
      interval: daily
    groups:
      kubernetes:
        patterns:
          - k8s.io/*
  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/actions/*/
    schedule:
      interval: daily
