/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ReportSummaryApplyConfiguration represents a declarative configuration of the ReportSummary type for use
// with apply.
type ReportSummaryApplyConfiguration struct {
	Pass  *int `json:"pass,omitempty"`
	Fail  *int `json:"fail,omitempty"`
	Warn  *int `json:"warn,omitempty"`
	Error *int `json:"error,omitempty"`
	Skip  *int `json:"skip,omitempty"`
}

// ReportSummaryApplyConfiguration constructs a declarative configuration of the ReportSummary type for use with
// apply.
func ReportSummary() *ReportSummaryApplyConfiguration {
	return &ReportSummaryApplyConfiguration{}
}

// WithPass sets the Pass field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Pass field is set to the value of the last call.
func (b *ReportSummaryApplyConfiguration) WithPass(value int) *ReportSummaryApplyConfiguration {
	b.Pass = &value
	return b
}

// WithFail sets the Fail field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Fail field is set to the value of the last call.
func (b *ReportSummaryApplyConfiguration) WithFail(value int) *ReportSummaryApplyConfiguration {
	b.Fail = &value
	return b
}

// WithWarn sets the Warn field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Warn field is set to the value of the last call.
func (b *ReportSummaryApplyConfiguration) WithWarn(value int) *ReportSummaryApplyConfiguration {
	b.Warn = &value
	return b
}

// WithError sets the Error field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Error field is set to the value of the last call.
func (b *ReportSummaryApplyConfiguration) WithError(value int) *ReportSummaryApplyConfiguration {
	b.Error = &value
	return b
}

// WithSkip sets the Skip field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Skip field is set to the value of the last call.
func (b *ReportSummaryApplyConfiguration) WithSkip(value int) *ReportSummaryApplyConfiguration {
	b.Skip = &value
	return b
}
