// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ReportConfigurationApplyConfiguration represents a declarative configuration of the ReportConfiguration type for use
// with apply.
type ReportConfigurationApplyConfiguration struct {
	Limits *LimitsApplyConfiguration `json:"limits,omitempty"`
}

// ReportConfigurationApplyConfiguration constructs a declarative configuration of the ReportConfiguration type for use with
// apply.
func ReportConfiguration() *ReportConfigurationApplyConfiguration {
	return &ReportConfigurationApplyConfiguration{}
}

// WithLimits sets the Limits field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Limits field is set to the value of the last call.
func (b *ReportConfigurationApplyConfiguration) WithLimits(value *LimitsApplyConfiguration) *ReportConfigurationApplyConfiguration {
	b.Limits = value
	return b
}
