// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/openreports/reports-api/pkg/client/clientset/versioned/typed/openreports.io/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeOpenreportsV1alpha1 struct {
	*testing.Fake
}

func (c *FakeOpenreportsV1alpha1) ClusterReports() v1alpha1.ClusterReportInterface {
	return newFakeClusterReports(c)
}

func (c *FakeOpenreportsV1alpha1) Reports(namespace string) v1alpha1.ReportInterface {
	return newFakeReports(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeOpenreportsV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
