// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/openreports/reports-api/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// ClusterReports returns a ClusterReportInformer.
	ClusterReports() ClusterReportInformer
	// Reports returns a ReportInformer.
	Reports() ReportInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// ClusterReports returns a ClusterReportInformer.
func (v *version) ClusterReports() ClusterReportInformer {
	return &clusterReportInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// Reports returns a ReportInformer.
func (v *version) Reports() ReportInformer {
	return &reportInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
