// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apisopenreportsiov1alpha1 "github.com/openreports/reports-api/apis/openreports.io/v1alpha1"
	versioned "github.com/openreports/reports-api/pkg/client/clientset/versioned"
	internalinterfaces "github.com/openreports/reports-api/pkg/client/informers/externalversions/internalinterfaces"
	openreportsiov1alpha1 "github.com/openreports/reports-api/pkg/client/listers/openreports.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ReportInformer provides access to a shared informer and lister for
// Reports.
type ReportInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() openreportsiov1alpha1.ReportLister
}

type reportInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewReportInformer constructs a new informer for Report type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewReportInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredReportInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredReportInformer constructs a new informer for Report type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredReportInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OpenreportsV1alpha1().Reports(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OpenreportsV1alpha1().Reports(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OpenreportsV1alpha1().Reports(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OpenreportsV1alpha1().Reports(namespace).Watch(ctx, options)
			},
		},
		&apisopenreportsiov1alpha1.Report{},
		resyncPeriod,
		indexers,
	)
}

func (f *reportInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredReportInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *reportInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisopenreportsiov1alpha1.Report{}, f.defaultInformer)
}

func (f *reportInformer) Lister() openreportsiov1alpha1.ReportLister {
	return openreportsiov1alpha1.NewReportLister(f.Informer().GetIndexer())
}
