name: Setup build env

inputs:
  unshallow:
    description: "git unshallow"
    default: 'true'
  free-disk-space:
    description: "free disk space"
    default: 'true'

runs:
  using: 'composite'
  steps:
    - uses: jlumbroso/free-disk-space@v1.3.1         # pin to the latest v1.3.1 release
      if: ${{ inputs.free-disk-space == 'true' }}
      with:
        tool-cache: true
        android: true
        dotnet: true
        docker-images: false
        large-packages: false
        swap-storage: false
    - shell: bash
      if: ${{ inputs.unshallow == 'true' }}
      run: |
        git fetch --prune --unshallow
    - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version-file: go.mod
    - shell: bash
      run: |
        go mod download